# Generated by Django 3.1.4 on 2021-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio_snippet',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
