# Generated by Django 3.1.4 on 2021-01-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_audio_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='audio_snippet',
        ),
        migrations.AddField(
            model_name='product',
            name='spotify_link',
            field=models.CharField(default=False, max_length=120),
        ),
    ]
