# Generated by Django 3.1.4 on 2021-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210101_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spotify_link',
            field=models.URLField(default=False, max_length=150),
        ),
    ]
