# Generated by Django 3.1.4 on 2021-01-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210101_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spotify_link',
            field=models.URLField(max_length=150),
        ),
    ]
