# Generated by Django 3.1.4 on 2021-01-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
    ]
