# Generated by Django 3.1.4 on 2021-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_address',
            field=models.ManyToManyField(to='cart.Address'),
        ),
    ]
