# Generated by Django 3.1.4 on 2021-01-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210117_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='funfun',
            field=models.FileField(default=False, upload_to='media'),
        ),
    ]
